#===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 254
  - 190
  - 127
  - 56

#===========================================================================
# allowed Formats
#===========================================================================
# '*' means any formats
formats: ['*']

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 250
  - 275
  - 300
  - 305
  - 310
  - 325
  - 340
  - 350
  - 375
  - 400
  - 500
  - 750
  - 1000
  - 1050
  - 1100
  - 1150
  - 1250
  - 1400
  - 1500
  - 1600
  - 1650
  - 1700
  - 1750
  - 1800
  - 1900
  - 2000
  - 2200
  - 2300
  - 2400
  - 2450
  - 2500
  - 2550
  - 2600
  - 2700
  - 2800
  - 2900
  - 2910
  - 2925
  - 2935
  - 2950
  - 3000
  - 3025
  - 3050
  - 3100
  - 3350
  - 3500
  - 3750
  - 4000
  - 4250
  - 4500
  - 4750
  - 4850
  - 5000
  - 5100
  - 5250
  - 5350
  - 5500
  - 5750
  - 6000
  - 6150
  - 6250
  - 6500
  - 6600
  - 6750
  - 6800
  - 6850
  - 6900
  - 7000
  - 7250
  - 7500
  - 8000
  - 8500
  - 8750
  - 9000
  - 9500
  - 9700
  - 10000
  - 11000
  - 11150
  - 11250
  - 11500
  - 11600
  - 11700
  - 11800
  - 11900
  - 12000
  - 12100
  - 12200
  - 12500
  - 12700
  - 13000
  - 13150
  - 13250
  - 13350
  - 13500
  - 13550
  - 13600
  - 13625
  - 13650
  - 13700
  - 13750
  - 13800
  - 14000
  - 14500
  - 15000
  - 15500
  - 16000
  - 16500
  - 17000
  - 17500
  - 18000
  - 20000
  - 20500
  - 20750
  - 21000
  - 21250
  - 21500
  - 22500
  - 25000
  - 25500
  - 26000
  - 26500
  - 26750
  - 27000
  - 27250
  - 27500
  - 27750
  - 28000
  - 28500
  - 29000
  - 30000
  - 32500
  - 35000
  - 37500
  - 40000
  - 50000
  - 60000
  - 75000
  - 100000
  - 200000
  - 300000
  - 500000
  - 525000
  - 545000
  - 550000
  - 560000
  - 575000
  - 590000
  - 625000
  - 640000
  - 650000
  - 670000
  - 750000
  - 850000
  - 1000000
  - 1050000
  - 1100000
  - 1250000
  - 1350000
  - 1500000
  - 1600000
  - 1750000
  - 2000000
  - 4000000
  - 8000000
  - 16000000
  - 32000000
  - 64000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !dnsMatch
    host: tile.openstreetmap.org

# the default fileName for the files downloaded from the servlet
outputFilename: CaerusGEO

layouts:
  #===========================================================================
  A4 portrait:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      pageSize: A4
      landscape: true
      marginLeft: 20
      marginRight: 20
      marginTop: 30
      marginBottom: 30
      items:
        - !map
          width: 735
          height: 510
          absoluteX: 74
          absoluteY: 565
        - !columns
          absoluteX: 375
          absoluteY: 31
          width: 100
          items:
            - !image
              maxHeight: 15
              url: '${configDir}/gen_by.png'
        - !columns
          absoluteX: 75
          absoluteY: 47
          width: 100
          items:
            - !image
              maxWidth: 100
              maxHeight: 25
              url: '${configDir}/compass.png'
            - !scalebar
              align: left
              maxSize: 220
              type: 'line'
              backgroundColor: #FFFFFF
      footer:
        height: 2
        items:
          - !columns
            items:
              - !text
                align: right
                fontSize: 10
                text: '${survey_info} | Page ${pageNum} of ${pageTot}'
  #===========================================================================
  LU portrait:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      pageSize: A4
      landscape: true
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: left
            text: '${reportTitle}'
      items:
        - !map
          spacingAfter: 0
          width: 760
          height: 450
        - !image
          align: left
          width: 200
          maxWidth: 200
          url: '${configDir}/new_legendv2.png'
      footer:
        height: 25
        items:
          - !columns
            items:
              - !text
                text: '${survey_info} | Generated By CaerusGeo'
                spacingAfter: 0
              - !text
                align: right
                text: 'Page ${pageNum} of ${pageTot}'
    lastPage:
      pageSize: A4
      landscape: true
      items:
        - !attributes
          source: data
          spacingAfter: 30
          tableConfig:
            cells:
              - padding: 4
              - row: '\d*[02468]'
                backgroundColor: #C0C0C0
              - row: 0
                backgroundColor: #868689
                fontColor: #FFFFFF
                paddingBottom: 6
          columnDefs:
            id:
              header: !text
                text: ID
                fontColor: white
              cell: !text
                text: '${id}'
            name:
              header: !text
                text: Name
                fontColor: white
              cell: !text
                text: '${name}'
            areause:
              header: !text
                text: Area Use
                fontColor: white
              cell: !text
                text: '${areause}'
            croptype:
              header: !text
                text: Crop Type
                fontColor: white
              cell: !text
                text: '${croptype}'
            amtdependents:
              header: !text
                text: Amount of Dependents
                fontColor: white
              cell: !text
                text: '${amtdependents}'
      footer:
        height: 50
        items:
          - !columns
            items:
              - !text
                align: left
                text: '${survey_info} | Generated By CaerusGeo'
              - !text
                align: right
                text: 'Page ${pageNum} of ${pageTot}'      
  #===========================================================================
  Open portrait:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      pageSize: A4
      landscape: true
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: left
            text: '${reportTitle}'
      items:
        - !map
          spacingAfter: 0
          width: 760
          height: 450
      footer:
        height: 25
        items:
          - !columns
            items:
              - !text
                text: '${survey_info} | Generated By CaerusOpen'
                spacingAfter: 0
              - !text
                align: right
                text: 'Page ${pageNum} of ${pageTot}'   
  #===========================================================================
  A0 portrait:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      rotation: true
      pageSize: A0
      landscape: true
      marginRight: 80
      marginLeft: 80
      header:
        height: 50
        items:
          - !text
            text: ' '
      items:
        - !map
          width: 3200
          height: 2125
        - !columns
          absoluteX: 75
          absoluteY: 140
          width: 500
          items:
            - !image
              maxWidth: 80
              maxHeight: 80
              url: '${configDir}/compass.png'
            - !scalebar
              align: left
              maxSize: 470
              type: 'line'
              backgroundColor: #FFFFFF
        - !columns
          absoluteX: 1430
          absoluteY: 105
          width: 500
          items:
            - !image
              maxHeight: 60
              url: '${configDir}/gen_by_wall.jpg'
      footer:
        height: 80
        items:
          - !columns
            items:
              - !text
                align: right
                fontSize: 36
                text: 'Wallmap | ${survey_info}'
  #===========================================================================
  A4 question:
  #===========================================================================
    # override the default outputFileName defined above
#    outputFilename: A4_Layout
    mainPage:
      pageSize: LETTER
      marginLeft: 47
      landscape: false
      header:
        height: 50
        items:
          - !text
            font: Helvetica
            fontSize: 30
            align: right
          - !text
              font: Helvetica
              fontSize: 10
              align: left
              text: '1:${scale}'
      items:
        - !map
          width: 548
          height: 660
